addons:
  code_climate:
    repo_token:
      secure: ronHNxm5mmNkASIMEBiIh9/QGZfilthqLYpNol01FppzI0MjOmYSN+DzZ1KI9TyDEB5QbQAuknRlI6SBjJYLcuUoSwmjOszB1a4VT5lPv9v+jm3G/9xXj2VnL8shmgTuKSOFOjjBr54jHUqdTMhfz8N925ZNpaldapY/WdRSzhcyylR/yJgP8NsivfQ/M3/A2L8kCqE7Of+0DGunQ7cuVZyCb7QKE9bkX6kb0Bd/nHWriBgdIjZsuakDbEzV68D4zR7fh4FgB5Gn2pBp1CRt10fDsfBhPGelnLrYu8N7sg8QtAk85QCj+/ACIojeGfQA/urT1vGyhCAUmVqhS6N0HzwNld9b+Lwd3iBY0E0plBCM9jouKI3o6fZWz4aWJzVMlyDM/Sh8jgnn7QvXuO/0b9Y71w7WxEanNsvLruI7OM76ZwAeDq+70gAPY6QdHVDwREQvPxtnShxkfLr5wQlukNW+3LJ1e7QS/xF7i6EZafhYgCSx9t4Z3BJ7CINZaZWGJKFeyPa5nwRmIDkwT4f4K5p0cRpEMBYzF1rd9XLPCFt+sK6WcpOLfTCFP7QkooEMQDTZhWX3SlUbWyxbjZEBRWlWrT+HNFt6fkxiw7TjUZ3S4MHpti/s26LbyZuW/iuoYcVbZ39n26D6z3xC4qFQb7sQfVmlaT6rTaXrxLQ3rX8=
language: node_js
node_js:
- node
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- npm install codeclimate-test-reporter -g
after_script:
- codeclimate-test-reporter <./coverage/lcov.info
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: lint
    script: make lint
  - stage: tests
    script: make test
